# Generated by Django 3.2.6 on 2022-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
