# Generated by Django 3.2.6 on 2022-01-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registered_workshop',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
