# Generated by Django 3.2.6 on 2021-11-28 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20211128_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='channel_name',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='User_Roooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.ManyToManyField(to='chat.Rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
