# Generated by Django 3.2.6 on 2021-11-28 18:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20211128_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Roooms',
            new_name='User_Rooms',
        ),
    ]
