# Generated by Django 3.2.6 on 2021-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_user_roooms_user_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ManyToManyField(to='chat.Rooms')),
            ],
        ),
        migrations.DeleteModel(
            name='User_Rooms',
        ),
    ]
