# Generated by Django 3.2.6 on 2021-11-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211129_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room_users',
        ),
    ]
