# Generated by Django 3.2.6 on 2021-11-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_delete_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
