# Generated by Django 3.2.6 on 2021-09-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20210902_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyqs',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
