# Generated by Django 3.2.6 on 2021-09-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_pyqs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_detail',
            name='reg_link',
            field=models.URLField(blank=True),
        ),
    ]
