# Generated by Django 3.2.6 on 2021-09-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_detail_reg_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PYQs',
            new_name='PYQ',
        ),
    ]
