# Generated by Django 3.2.6 on 2021-09-03 16:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20210903_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_detail',
            name='important_dates',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam_detail',
            name='syllabus',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
