# Generated by Django 3.2.6 on 2021-09-11 11:35

from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20210903_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pyqs',
            old_name='link',
            new_name='question_link',
        ),
        migrations.AddField(
            model_name='pyqs',
            name='answer_link',
            field=models.URLField(blank=re.RegexFlag['TEMPLATE'], null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pyqs',
            name='phase',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
