# Generated by Django 3.2.6 on 2021-09-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20210911_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyqs',
            name='answer_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pyqs',
            name='question_link',
            field=models.URLField(),
        ),
    ]
