# Generated by Django 3.2.6 on 2021-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20210911_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate_Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('gate_paper', models.CharField(max_length=100)),
                ('syllabus', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
