# Generated by Django 3.2.6 on 2021-12-11 06:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_gate_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_detail',
            name='exam_content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam_detail',
            name='syllabus',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
