# Generated by Django 3.2.6 on 2021-12-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20211211_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_detail',
            name='exam_content',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
