# Generated by Django 3.2.6 on 2022-01-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_alter_feeds_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds',
            name='author',
        ),
    ]
