# Generated by Django 3.2.6 on 2022-01-22 09:18

from django.db import migrations, models
import feeds.models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_alter_feeds_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds',
            name='image',
        ),
        migrations.AddField(
            model_name='feeds',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=feeds.models.upload_to, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
