# Generated by Django 3.2.6 on 2021-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20210813_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='content',
            field=models.TextField(),
        ),
    ]
