# Generated by Django 3.2.6 on 2021-08-06 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password1',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password2',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='program',
            field=models.CharField(choices=[('BTECH', 'BTech.'), ('MTECH', 'Mtech'), ('MBA', 'MBA'), ('PhD', 'PhD'), ('RESEARCH', 'Research')], default='BTECH', max_length=40),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
