# Generated by Django 3.2.6 on 2021-08-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20210806_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='users',
            name='department',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='password1',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='password2',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
