# Generated by Django 3.2.6 on 2021-08-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20210806_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='section',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
