# Generated by Django 3.2.6 on 2021-08-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_users_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password1',
            new_name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password2',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
