# Generated by Django 3.2.6 on 2021-08-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_auto_20210806_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password1',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password2',
            new_name='password',
        ),
    ]
