# Generated by Django 3.2.6 on 2021-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_auto_20210806_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AddField(
            model_name='users',
            name='password1',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
