# Generated by Django 3.2.6 on 2021-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_auto_20210806_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contact_number',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
