# Generated by Django 3.2.6 on 2022-01-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hide_email',
            field=models.BooleanField(default=False),
        ),
    ]
