# Generated by Django 3.2.6 on 2022-01-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_alter_account_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
